language: python

python:
  - 3.5

install:
  - make install_requirements
  - pip install coveralls

script:
  - coverage run --source=flashcard -m unittest -v flashcard/tests/*.py

after_success:
  - coveralls
